# Generated by Django 5.0 on 2023-12-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdooConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('odoo_url', models.URLField()),
                ('odoo_database', models.CharField(max_length=255)),
                ('odoo_username', models.CharField(max_length=255)),
                ('odoo_password', models.CharField(max_length=255)),
            ],
        ),
    ]
